name: endless_runner
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  flame_audio: ^2.10.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  nes_ui: ^0.20.0
  google_fonts: ^6.2.0
  logging: ^1.2.0

dev_dependencies:
  flame_test: ^1.16.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.25.0

flutter:
  uses-material-design: true
